steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/carbide-trees-282519/inter-observer', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/carbide-trees-282519/inter-observer']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '--image', 'gcr.io/carbide-trees-282519/inter-observer', '--region', 'europe-west4', '--platform', 'managed', '--memory', '2Gi']
images:
- gcr.io/PROJECT_ID/IMAGE